services:
  web:
    container_name: web
    image: ghcr.io/mmichaellangelo/phone_sensordata/web:latest
    ports: 
      - 80:80
  api:
    container_name: api
    image: ghcr.io/mmichaellangelo/phone_sensordata/api:latest
    expose: 
      - 8080
  redis:
    container_name: redis
    image: redis:alpine
    expose: 
      - 6379
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      WATCHTOWER_POLL_INTERVAL: 60  # Check for updates every minute
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always