name: Docker Build and Push to GHCR

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push web image
        uses: docker/build-push-action@v4
        with:
          context: frontend
          target: prod
          push: true
          tags: |
            ghcr.io/mmichaellangelo/phone_sensordata/web:latest
            ghcr.io/mmichaellangelo/phone_sensordata/web:${{ github.sha }}

      - name: Build and push api image
        uses: docker/build-push-action@v4
        with:
          context: backend
          target: prod
          push: true
          tags: |
            ghcr.io/mmichaellangelo/phone_sensordata/api:latest
            ghcr.io/mmichaellangelo/phone_sensordata/api:${{ github.sha }}

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan symphoney.xyz >> ~/.ssh/known_hosts
      
      - name: Update server
        run: |
          ssh -i ~/.ssh/id_ed25519 root@symphoney.xyz "
            cd /app
            curl -sO https://raw.githubusercontent.com/.../compose.prod.yml
            docker compose -f compose.prod.yml up -d --force-recreate
          "
